package com.sanxin.common.dao;

import com.sanxin.common.entity.Datasource;
import com.sanxin.common.entity.DatasourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int countByExample(DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int deleteByExample(DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int insert(Datasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int insertSelective(Datasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    List<Datasource> selectByExample(DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    Datasource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Datasource record, @Param("example") DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Datasource record, @Param("example") DatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Datasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Datasource record);
}