package com.sanxin.common.entity;

public class Datasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource.datakey
     *
     * @mbggenerated
     */
    private String datakey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource.datadriver
     *
     * @mbggenerated
     */
    private String datadriver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource.dataurl
     *
     * @mbggenerated
     */
    private String dataurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource.datauser
     *
     * @mbggenerated
     */
    private String datauser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datasource.datapwd
     *
     * @mbggenerated
     */
    private String datapwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource.id
     *
     * @return the value of datasource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource.id
     *
     * @param id the value for datasource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource.datakey
     *
     * @return the value of datasource.datakey
     *
     * @mbggenerated
     */
    public String getDatakey() {
        return datakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource.datakey
     *
     * @param datakey the value for datasource.datakey
     *
     * @mbggenerated
     */
    public void setDatakey(String datakey) {
        this.datakey = datakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource.datadriver
     *
     * @return the value of datasource.datadriver
     *
     * @mbggenerated
     */
    public String getDatadriver() {
        return datadriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource.datadriver
     *
     * @param datadriver the value for datasource.datadriver
     *
     * @mbggenerated
     */
    public void setDatadriver(String datadriver) {
        this.datadriver = datadriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource.dataurl
     *
     * @return the value of datasource.dataurl
     *
     * @mbggenerated
     */
    public String getDataurl() {
        return dataurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource.dataurl
     *
     * @param dataurl the value for datasource.dataurl
     *
     * @mbggenerated
     */
    public void setDataurl(String dataurl) {
        this.dataurl = dataurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource.datauser
     *
     * @return the value of datasource.datauser
     *
     * @mbggenerated
     */
    public String getDatauser() {
        return datauser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource.datauser
     *
     * @param datauser the value for datasource.datauser
     *
     * @mbggenerated
     */
    public void setDatauser(String datauser) {
        this.datauser = datauser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datasource.datapwd
     *
     * @return the value of datasource.datapwd
     *
     * @mbggenerated
     */
    public String getDatapwd() {
        return datapwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datasource.datapwd
     *
     * @param datapwd the value for datasource.datapwd
     *
     * @mbggenerated
     */
    public void setDatapwd(String datapwd) {
        this.datapwd = datapwd;
    }
}