package com.sanxin.common.entity;

import java.util.ArrayList;
import java.util.List;

public class DatasourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table datasource
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table datasource
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table datasource
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public DatasourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table datasource
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatakeyIsNull() {
            addCriterion("datakey is null");
            return (Criteria) this;
        }

        public Criteria andDatakeyIsNotNull() {
            addCriterion("datakey is not null");
            return (Criteria) this;
        }

        public Criteria andDatakeyEqualTo(String value) {
            addCriterion("datakey =", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyNotEqualTo(String value) {
            addCriterion("datakey <>", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyGreaterThan(String value) {
            addCriterion("datakey >", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyGreaterThanOrEqualTo(String value) {
            addCriterion("datakey >=", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyLessThan(String value) {
            addCriterion("datakey <", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyLessThanOrEqualTo(String value) {
            addCriterion("datakey <=", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyLike(String value) {
            addCriterion("datakey like", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyNotLike(String value) {
            addCriterion("datakey not like", value, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyIn(List<String> values) {
            addCriterion("datakey in", values, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyNotIn(List<String> values) {
            addCriterion("datakey not in", values, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyBetween(String value1, String value2) {
            addCriterion("datakey between", value1, value2, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatakeyNotBetween(String value1, String value2) {
            addCriterion("datakey not between", value1, value2, "datakey");
            return (Criteria) this;
        }

        public Criteria andDatadriverIsNull() {
            addCriterion("datadriver is null");
            return (Criteria) this;
        }

        public Criteria andDatadriverIsNotNull() {
            addCriterion("datadriver is not null");
            return (Criteria) this;
        }

        public Criteria andDatadriverEqualTo(String value) {
            addCriterion("datadriver =", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverNotEqualTo(String value) {
            addCriterion("datadriver <>", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverGreaterThan(String value) {
            addCriterion("datadriver >", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverGreaterThanOrEqualTo(String value) {
            addCriterion("datadriver >=", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverLessThan(String value) {
            addCriterion("datadriver <", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverLessThanOrEqualTo(String value) {
            addCriterion("datadriver <=", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverLike(String value) {
            addCriterion("datadriver like", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverNotLike(String value) {
            addCriterion("datadriver not like", value, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverIn(List<String> values) {
            addCriterion("datadriver in", values, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverNotIn(List<String> values) {
            addCriterion("datadriver not in", values, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverBetween(String value1, String value2) {
            addCriterion("datadriver between", value1, value2, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDatadriverNotBetween(String value1, String value2) {
            addCriterion("datadriver not between", value1, value2, "datadriver");
            return (Criteria) this;
        }

        public Criteria andDataurlIsNull() {
            addCriterion("dataurl is null");
            return (Criteria) this;
        }

        public Criteria andDataurlIsNotNull() {
            addCriterion("dataurl is not null");
            return (Criteria) this;
        }

        public Criteria andDataurlEqualTo(String value) {
            addCriterion("dataurl =", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotEqualTo(String value) {
            addCriterion("dataurl <>", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlGreaterThan(String value) {
            addCriterion("dataurl >", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlGreaterThanOrEqualTo(String value) {
            addCriterion("dataurl >=", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlLessThan(String value) {
            addCriterion("dataurl <", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlLessThanOrEqualTo(String value) {
            addCriterion("dataurl <=", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlLike(String value) {
            addCriterion("dataurl like", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotLike(String value) {
            addCriterion("dataurl not like", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlIn(List<String> values) {
            addCriterion("dataurl in", values, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotIn(List<String> values) {
            addCriterion("dataurl not in", values, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlBetween(String value1, String value2) {
            addCriterion("dataurl between", value1, value2, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotBetween(String value1, String value2) {
            addCriterion("dataurl not between", value1, value2, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDatauserIsNull() {
            addCriterion("datauser is null");
            return (Criteria) this;
        }

        public Criteria andDatauserIsNotNull() {
            addCriterion("datauser is not null");
            return (Criteria) this;
        }

        public Criteria andDatauserEqualTo(String value) {
            addCriterion("datauser =", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserNotEqualTo(String value) {
            addCriterion("datauser <>", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserGreaterThan(String value) {
            addCriterion("datauser >", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserGreaterThanOrEqualTo(String value) {
            addCriterion("datauser >=", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserLessThan(String value) {
            addCriterion("datauser <", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserLessThanOrEqualTo(String value) {
            addCriterion("datauser <=", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserLike(String value) {
            addCriterion("datauser like", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserNotLike(String value) {
            addCriterion("datauser not like", value, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserIn(List<String> values) {
            addCriterion("datauser in", values, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserNotIn(List<String> values) {
            addCriterion("datauser not in", values, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserBetween(String value1, String value2) {
            addCriterion("datauser between", value1, value2, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatauserNotBetween(String value1, String value2) {
            addCriterion("datauser not between", value1, value2, "datauser");
            return (Criteria) this;
        }

        public Criteria andDatapwdIsNull() {
            addCriterion("datapwd is null");
            return (Criteria) this;
        }

        public Criteria andDatapwdIsNotNull() {
            addCriterion("datapwd is not null");
            return (Criteria) this;
        }

        public Criteria andDatapwdEqualTo(String value) {
            addCriterion("datapwd =", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdNotEqualTo(String value) {
            addCriterion("datapwd <>", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdGreaterThan(String value) {
            addCriterion("datapwd >", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdGreaterThanOrEqualTo(String value) {
            addCriterion("datapwd >=", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdLessThan(String value) {
            addCriterion("datapwd <", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdLessThanOrEqualTo(String value) {
            addCriterion("datapwd <=", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdLike(String value) {
            addCriterion("datapwd like", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdNotLike(String value) {
            addCriterion("datapwd not like", value, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdIn(List<String> values) {
            addCriterion("datapwd in", values, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdNotIn(List<String> values) {
            addCriterion("datapwd not in", values, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdBetween(String value1, String value2) {
            addCriterion("datapwd between", value1, value2, "datapwd");
            return (Criteria) this;
        }

        public Criteria andDatapwdNotBetween(String value1, String value2) {
            addCriterion("datapwd not between", value1, value2, "datapwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table datasource
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table datasource
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}